### ISSUE TITLE
[hbss] a remark regarding scope

### ISSUE THREAD

**Issue by brunojav** [w3c/websec#106]
Line 110, paragraph 2.Problem Statement : "issue and use identity keys (whether they [...]"
    >> we put issuance out of scope no ?

**Comment by brunojav** [comment]
In addition, paragraph 4.2.1.5, do we keep "generateKey" and "ImportKey" methods ?

**Comment by acouvert** [comment]
I would say yes, the idea is to keep the same functionalities offered by the current WebCrypto API but ran into an hardware based secure device instead. I know for now we assume that the keys are pre-provisionned, to keep things simpler, and so generateKey and ImportKey are not yet useful. But for me, those features would make sense later in an hbss environment that's why I chose to also add the optional parameter to those two functions as well.

**Comment by vgalindo** [comment]
@brunojav can you live with those functions integrated in the report, as suggested by @acouvert ?
@sbahloul If yes, I suggest we close this issue.

**Comment by brunojav** [comment]
yes, I can totally live with it and I do agree with Aurelien that for future use there is a point to include "write" features. My question was only regarding coherence of the document.
In a way, credentials generation is more complex and can be kept for future discussions.
