### ISSUE TITLE
Common mechanism for accessing hardware tokens

### ISSUE THREAD

**Issue by rigow** [w3c/websec#23]
In a first step and in order to cater to the existing mechanisms, it was discussed whether HASEC would be able to use "native messaging" as suggested by Martin Paljak and @cyberphone. This was also recently discussed in WebAppSec and a first draft by @mikewest in https://github.com/mikewest/cors-rfc1918 was issued that advanced the discussion on that question

**Comment by wayneca** [comment]
There was a related discussion in #8 -- better to have a discussion like this with a relevant title.

My comment on this is at [https://github.com/w3c/websec/issues/8#issuecomment-174021754](https://github.com/w3c/websec/issues/8#issuecomment-174021754)

The SysApps WG (now closed) had in its charter a Secure Element API spec for sending arbitrary messages to a Secure Element.  My impression was that had little support, especially from Browser vendors who would need to implement it.  Part of that I think was due to security concerns.

I'd think the major challenge for this proposed group is to get Web Browser vendors interested in participating.  I haven't seen any of them in these discussions yet.  I'd think the proposed group needs at least a couple of the big 4 to be successful.  Bringing Secure Element API back doesn't seem a good way to get to that.

[https://www.w3.org/2012/sysapps/](https://www.w3.org/2012/sysapps/)

**Comment by cyberphone** [comment]
@rigow @wcarr

> I'd think the major challenge for this proposed group is to get Web Browser vendors interested in participating. I haven't seen any of them in these discussions yet.

Since there are no input specifications, there's nothing to discuss.

I would consider creating a HW Security IG and then if an acceptable specification surfaces spawn a WG for that purpose or make it a part of an existing WG if that's better.

**Comment by martinpaljak** [comment]
@wcarr I think that nobody is thinking that SE level API would be meaningful or is something that is (supposed to be) discussed. I guess nobody outside of smart card vendors gets excited when they hear "APDU" and rightfully so. Instead of trying to figure out some kind of fancy and super abstract API for accessing secure hardware and expect browsers to implement it maybe, in the future, it makes sense to see what might be the common ground with browser vendors that might work and not require massive buy-in for something radically new.

Instead of putting vague ideas on paper, native messaging is something that can support ideas with POC-s _even today_.

**Comment by cyberphone** [comment]
Since the lack of input specifications is an issue, here is a minimal specification (_completely unrelated to Native Messaging_) for supporting HW-protected keys in WebCrypto:

**crypto.subtle.generateAttestedKey**(_algorithm_,_keyUsages_,_nonce_).then(function(_key_, _attestation_)

This method is derived from **crypto.subtle.generateKey**(-_extractable_ +_nonce_),  while _attestation_ is approximately a copy of the scheme used by U2F.  That is, _attestation_ vouches for the "quality" of the key storage.

@wcarr Would this work or do you envision something entirely different?

**Comment by wayneca** [comment]
@martinpaljak I don't see anything in the proposed charter that would support sending APDUs.(other than this Issue trying to get that in).

@cyberphone In considering charters, people can discuss whether they're interested in an approach without going into the details of a sample spec.  e.g. do they care about the use case at all?  (IGs can't create specs - no patent policy - but a CG could, and that's often a consideration in approving a charter, whether it needs incubation work first to ensure its feasible).

**Comment by wayneca** [comment]
@cyberphone I made a pull request #25 to modify the discovery and attestation restricted scope item to make it clearer.

**Comment by rigow** [comment]
merged your pull request
