### ISSUE TITLE
[hasec charter] wild card deliverable for Web Payments

### ISSUE THREAD

**Issue by wayneca** [w3c/websec#35]
The restricted scope items are supposed to be narrowly scoped to be able to determine what types of technologies may be licensed.  They should not be open ended.

> Web payments access: Cooperate with the Web payments WG to allow access to payment related hardware via the hardware APIs developed within the HASEC Group.

The restricted scope item pasted above is not meant to be a specific kind of spec.  The item pasted in above seems to be access to anything that could be of use.  If it belongs anywhere in the charter, it should be in the more general scope section that describes the wider scope for non-Recommendation deliverables.  If, working with the Web Payments WG, it is determined that the Charter restricted scope items need to be expanded, then the WG should recharter when it is known what it is.   It shouldn't have a wild card to create any type of Recommendation it later decides it wants to create.

I think there would be objections to this item in the Advisory Committee Review in the Charter approval process for being too open ended and vague.

**Comment by rigow** [comment]
Currently, the text says: "_The Working Group will liaise with the Web Payments Working Group on web payments access. The expected non normative deliverables with Web Payments WG are use case and an architecture document, focusing on payment integration in the web payment API designed when payment means relies on hardware._ for unrestricted. So would removing the restricted text still address one of @vgalindo 's central use cases? Because it looks like it says that the Payments WG will have to address the connection to the hardware. But the Payment WG only makes connections to a wallet. And that wallet has then to connect to the hardware. This is not addressed with the current wording. 
So I think those having a clue about what is intended should suggest a new wording with a more precise repartition on what this is going to do. I imagine this wants to provide either direct access to hardware payment tools or via the wallet of the web payments WG

**Comment by vgalindo** [comment]
@rigow @drogers lets fix that by removing the sentence from the restricted scope, we have the 3.2 paragraphe addressing that already

**Comment by rigow** [comment]
Done with PR #57
