### ISSUE TITLE
[hasec charter] SysApp Secure Element access to hardware tokens

### ISSUE THREAD

**Issue by wayneca** [w3c/websec#36]
From the Restricted Scope Items

> Specify a common mechanism for accessing hardware tokens

The SysApps WG tried to create a common mechanism for accessing hardware tokens by defining a message channel to secure elements that arbitrary messages could be sent on.  There was no support at all for that from the Browser vendors (and not much support from anyone else).  There were concerns about the security of allowing this type of access from a Web page.

I think including this would lead to a Formal Objection in the W3C Advisory Committee Review in the Charter approval process.  That doesn't mean it wouldn't be approved anyway.  But, if a goal is to try to get major Browser vendors on board in this proposed group, this doesn't seem a good way to do it.  These more controversial specs could be developed in its own Community Group to show it has support before being done in a Working Group.

**Comment by vgalindo** [comment]
@rigo @drogersuk lets find a better wording for clarifying the expected mecanism (not a permission, but rather a contextual information, linked with origin that avoids replay)
Action : me to suggest something...

**Comment by vgalindo** [comment]
@rigow @drogersuk @wcarr 
Proposed resolution: 
I suggest that we *_remove *_ that item from the list of deliverables. The objective we are looking for is to make sure that access to hardware token services is controlled and can not be replayed, this may not lead to developing an actual specification, but rather describe a set of security measures in the APIs we will develop (aka, service session id ...) based on common sense.

**Comment by wayneca** [comment]
+1 for removing it as a separate item

**Comment by wseltzer** [comment]
@rigow, @drogersuk are we good with https://github.com/w3c/websec/pull/62 ?

**Comment by rigow** [comment]
Accepted proposed fix as agreed with the chairs with PR #62

**Comment by martinpaljak** [comment]
As has been told many times, exposing a plain "APDU pipe" to secure elements (thus implying that a secure element MUST be something that speaks APDU-s) as a uniform transport channel (and exposing this to the web) was, is, and will be a mediocre idea, for reasons too many to repeat here.

But removing a uniform access approach from the deliverables list basically means (at least to me) that intentionally a layered architecture is discarded. So to get browser vendors interested in whatever this group has to offer (as there already is FIDO that solves if not everything then at least half of problems?), instead of offering a meaningful and achievable path for implementation, there shall (maybe) be X possible deliverables to be implemented _in the browser_ to be meaningful. 

As a developer I find this either bad design and/or architecture astronautics, successful designs thrive for simplicity.

The remaining list does include Secure Worker item, that basically defines (vaguely) a similar approach "...this would communicate to the calling Web page code using a message channel provided by the User Agent/Browser...". I don't know if the specific proposal of using native messaging style would be considered as a subset of this or not, nor am I proficient in the terminology used by w3c, that's why I'd like to explicitly have the "build us a pipe, we build the essence" deliverable.

**Comment by cyberphone** [comment]
@martinpaljak (and @wcarr @rigow @draggett @vgalindo @drogersuk) It is obvious that the "pipe" as you call it is where the _market_ is going.

In Android 6, App Linking has been upgraded (http://developer.android.com/training/app-links/index.html) and the recent Android fix for "talking back" to the Web suggested (and implemented) by Google for the Web Payment API effort shows that this feature is no longer an option; it is a "must have".

However, that the Chrome desktop version uses an entirely different "pipe" while the other browser vendors have nothing on their plates indicate that this is an _excellent task for standardization_.  Where (and how) exactly this standardization happens _is of no importance to the market_.

If a standard "competes" with other standards is not a problem; it happens all the time.  For the "pipe" there are (with FIDO as sole and very limited exception), currently no contenders.

**Comment by sepulo** [comment]
@cyberphone Browsers made a very sluggish move to handing SE and the requirement has already emerged. They let the requirement grow and now push them toward a hasty decision. Although providing an APDU pipe seems a hasty design decision but - in absence of a better suggestion - appears inescapable.

**Comment by cyberphone** [comment]
@sepulo If you follow the link I provided you will find that it is not a pipe to SEs that I and @martinpaljak suggest, but a pipe from the Web to the Native/App layer.  This is similar (but much better) than the (now deprecated) NPAPI and ActiveX solutions.  Such a scheme would enable innovation by third parties rather than total dependence on 2-3 browser vendors.
