### ISSUE TITLE
Comments from Jörg Heuer

### ISSUE THREAD

**Issue by rigow** [w3c/websec#9]
I find the charter pretty good already and I'd have no objections. Nevertheless here are a few comments and proposals for additions:

I'd add 'Entitlements' to the list of Goals, which would encompass keys, tickets, etc. These are authorizations which are not derived from an identity, but from mere possession. Ticketing already takes place on the basis of SEs e.g.

In the wake of the introduction of entitlements, privacy, pseudonymity and anonymity should be encompasses in the Scope section.

2.1. should respectively not only cover 'Identity semantics' (which I find kind of unwieldy and unclear) but also said 'entitlements' allowing the owner/ operator of the hardware to get access to resources.

I like the way you avoid having to say something about the provisioning of crypto and service code to the secure hardware! 

3.3 made me nervous somehow - would it be possible to state an example of what these deliverables could be?

4.1. should probably refer to the NFC group if it still is around and does what I'd expect such a group to do... (but I am totally unaware of their current status, admittedly.)

**Comment by vgalindo** [comment]
About ticketing
I suggest that we keep this in the scope for study, aka, not promising any delivery, our use cases list is already huge. I would put that at the same level as payment. We know we need to do something about it, but we dont know what. The 18 months of the charter will allow us to describe use cases and technical requirements, I guess. 
--> we need to think about the wording for ticketing

**Comment by vgalindo** [comment]
About comment : 
In the wake of the introduction of entitlements, privacy, pseudonymity and anonymity should be encompasses in the Scope section.
--> proposition : 
remove "Protection against fingerprinting (tracking users through information about their Browser environment) must be a prime consideration in all APIs."  and replace by : 
"Because web app using services providing some security sensitive functions may be sensitive to the users, this WG will take special care to make sure that the deliverables do not break user privacy and potential anonymity. As such, deliverables will take special care of fingerprinting and tracking threats. In addition, some mechanisms will be associated to make sure security functions will be used under the  user control.

**Comment by rigow** [comment]
Done

**Comment by wayneca** [comment]
> 3.3 made me nervous somehow - would it be possible to state an example of 
> what these deliverables could be?

Suggested a wording clarification in #11 

I think with W3C's use of "Recommendation" instead of "Specification", the original text could look like other specs could be created.  That couldn't happen in W3C, but it wasn't clear enough.

**Comment by wayneca** [comment]
> 4.1. should probably refer to the NFC group if it still is around and does 
> what I'd expect such a group to do... (but I am totally unaware of their current status, admittedly.)

The [NFC WG](http://www.w3.org/2012/nfc/) is gone.  There is a [Web NFC Community Group](https://www.w3.org/community/web-nfc/).   In the past, Charters have listed a huge laundry list of WGs because every WG is relevant in some way, so there has been a move towards listing just particularly strong connections.  (like every WG should talk to the accessiblity, I18N, security and privacy folks).

Does this proposed WG need to talk to the Web NFC CG in particular?  Would that be covered through their interaction with the Web Payments WG?

(by the way, all those groups should have links.  I'll do a PR.)

**Comment by vgalindo** [comment]
@rigow I suggest we close this issue, as being resolved.

**Comment by rigow** [comment]
as indicated the comment has been addressed
