### ISSUE TITLE
2. Problem Statement

### ISSUE THREAD

**Issue by mark-orz** [w3c/websec#91]
"This document is targeting to define the next generation Javascript API for hardware based keys management and usage, including two specific features :the secure transaction confirmation and the secure credential storage. "
Change to
"This document aims to define the next generation Javascript API for two specific requirements for hardware based key management and usage: Secure transaction confirmation and Secure credential storage."

"Those two technologies were identified, because they are key to the corresponding underlying components requirements to re-enable a strong security and identity ecosystem."
Change to
"These two requirements have been identified by the Hardware Based Secure Services Community Group as being as key to enabling a strong security and identity ecosystem."

"As an example: Let's consider that a domain foo.com issues a key. Because the keys won't be accessible with a Javascript API from any domain, we have to design a secure system where the domain bar.com is allowed to use this key."
Change to
"For example: Suppose that a domain foo.com issues a key. Because the key is not accessible by Javascript API from another domain, we have to design a secure system where the domain bar.com is allowed to use this key."

"This first version of the report will not address this issue but will focus on: 
•pre-existing X509 certificates accessible under the full control of the end-user to any transaction confirmation request.
•any API issued key MUST only be managed and used by its origin
Further extension will be added to authorize various origins to use and manage a particular key."
Change to
"In this document, we assume that:
•pre-existing keys and X509 certificates are under the full control of the end-user
•any API issued key MUST only be managed and used by its own origin
Extensions will be added later to authorize various origins to use and manage a particular key."

"The user verification method is out of scope of this specification" defines three modes: presence, os, active.
"The Relying Party should take care that:" refers to three modes: passive, presence, os.
Fix this.

**Comment by cyberphone** [comment]
> "For example: Suppose that a domain foo.com issues a key. Because the key is not accessible by Javascript API from another domain, we have to design a secure system where the domain bar.com is allowed to use this key."
> 
> "This first version of the report will not address this issue but will focus on: 

It seems unwise mentioning what next versions should be capable of without having analysed if there actually is a reasonable solution to this problem.

> pre-existing X509 certificates accessible under the full control of the end-user to any transaction confirmation request.

This use-case has already been dismissed by the browser vendors.

**Comment by sbahloul** [comment]
> It seems unwise mentioning what next versions should be capable of without having analysed if there actually is a reasonable solution to this problem.

We discuss about that and try to define various approaches (browser based  with user explicit consent like cameras, organized protocol like the following: https://github.com/w3c/websec/blob/gh-pages/hb-secure-services/SafranIdentitySecurity_Authorization-model-for-Javascript-usage-of-hardware-based-keys.pdf) which may not be the right one but we definitely think there is an acceptable approach.

> This use-case has already been dismissed by the browser vendors.

Yes but this was with an APDU based API meaning that the browser was unable to give any meaning to the API goals and to act on behalf of the end-user.

**Comment by sbahloul** [comment]
> "The user verification method is out of scope of this specification" defines three modes: presence, os, active.
> "The Relying Party should take care that:" refers to three modes: passive, presence, os.
> Fix this.
> Proposition: 
> - Add to the first section: "... the terminal without any user interaction (passive). ..."
> - Add to the second section: "Only the active option will guarantee that the user with the right knowledge or biometric characteristic is behind the user-agent."

**Comment by cyberphone** [comment]
@sbahloul "Transaction Confirmation JS API" sounds nice but is actually pretty fishy.

Since Apple already have a productized solution offering HW security and transaction confirmation, it seems that this effort is about reinventing the wheel.

**Comment by sbahloul** [comment]
@cyberphone You are welcome to contribute and share your thoughts within the Community Group (https://www.w3.org/community/hb-secure-services/participants) - the call is tomorrow at 4PM French time :). 
At this time the group is working to define a proposition to leverage existing SE/smartcards and make  use of SE/TEE available in the different devices available in everyone's pocket.

**Comment by cyberphone** [comment]
@sbahloul I'm unfortunately not available 4PM but what I'm proposing is by no means new information, it just got a bit more relevant after witnessing _Apple taking the same path_ (https://developer.apple.com/videos/play/wwdc2016/703/), albeit using a _proprietary_, _application-specific_ solution.  The core problems you are facing include:
- There is currently no "Trusted Code" concept for the Web which even makes trivial things like reading a PIN-code in a _trustworthy_ manner impossible
- The famous "Web Security Model" works great for browser mechanics like <code>fetch()</code> but doesn't really match <i>users</i> who aren't necessarily constrained to using a specific credential for each domain.  In fact, _multi-domain credentials are already firmly established_ in most (but not all) countries having eID programs like Sweden and Estonia
- By building on a non-granular, static, and use-case independent browser security model, you will run into difficult design consderations since (for example) _payments and authentication have quite different privacy characteristics_
- Standardizing UIs like (probably) is required for digital signature applications has proved to be a major source of conflicts

One solution to these problems is accepting that the Web and browsers have certain undeniable qualities but that native applications (aka "Apps") have _another_ set of features.  By _combining_ these technologies through a simple and standardized communication facility, you can get _the best of both worlds_.  Here are a couple of activities working on such schemes:

https://www.w3.org/community/browserext/
https://github.com/cyberphone/web2native-bridge

Converted into practice it would mean that each community, country, etc could design the security applications _they_ want, and that without being stuck in endless standardization processes which also have shown a tendency to not work at all.

The following posting by Tim Berners-Lee shows that not even the _Inventor of the Web_ has much of a say against the browser vendors:
https://lists.w3.org/Archives/Public/www-tag/2015Sep/0000.html
This (now _removed_) security application would without doubt be possible to resurrect through the alternatives mentioned above.

I.e. what is a useful security application or not should be left (with some constraints...) to the "market" to decide rather than by committees (which typically have limited insight and interest in the actual problem space).  

From a browser vendor's perspective this is also about keeping the browser platform in shape by removing unnecessary "bloat".

**Comment by cyberphone** [comment]
Anne van Kesteren (a Mozilla web architect and esteemed W3C member) have expressed the following thoughts which supports my claim that powerful APIs in the Web like HB-Secure-Services are unlikely to happen: https://annevankesteren.nl/2016/07/web-computing

What he is missing is that there are no unsolvable problems problems combining the Web and Store worlds.  Well, bugs will happen and some apps may not do what the user expects but that is not the same as "broken architecture".

**Comment by cyberphone** [comment]
https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/13612338-native-messaging

**Comment by vgalindo** [comment]
I suggest we close that issue as it has a corresponding commit and no new information has been brought.
